[App]
; Set to true if running the compiled version
IsBuilt=false

[Navigation]
; The URL or file path to load on startup.
; Use http://localhost:3000 for development.
; Examples: 
; http://gui.localhost/index.html
; file:///${A_ScriptDir}\settings\dist\index.html
StartupUrl=http://gui.localhost/index.html
; StartupUrl=http://localhost:3000

[Network]
; Enable adblock globally
AdblockEnabled=true
