name: Publish Auto-Update Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*" # Triggers workflow only when a version tag like "v1.0.0" is pushed

jobs:
  build:
    permissions:
      contents: write # Needed to create the GitHub release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/BingeKit.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
